name: Optimize map and deploy

on:
  push:
    branches:
      - master

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Optimize map
        uses: thecodingmachine/map-optimizer-action@master

      - name: Bash
        run: |
          ls -al
          git config --global user.email "githubactions@reaktor23.org"
          git config --global user.name "Github Actions"
          git checkout master
          git commit -am "Adding files"

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: .
          BASE_BRANCH: master
